/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CHIP = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_IN = 4,
  anon_sym_COMMA = 5,
  anon_sym_SEMI = 6,
  anon_sym_OUT = 7,
  anon_sym_PARTS = 8,
  anon_sym_COLON = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_EQ = 12,
  sym_identifier = 13,
  sym_comment = 14,
  sym_source_file = 15,
  sym__definition = 16,
  sym_chip_definition = 17,
  sym_chip_header = 18,
  sym_in_section = 19,
  sym_out_section = 20,
  sym_chip_body = 21,
  sym_part = 22,
  sym_connection = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_in_section_repeat1 = 25,
  aux_sym_out_section_repeat1 = 26,
  aux_sym_chip_body_repeat1 = 27,
  aux_sym_part_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CHIP] = "CHIP",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_IN] = "IN",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_OUT] = "OUT",
  [anon_sym_PARTS] = "PARTS",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_chip_definition] = "chip_definition",
  [sym_chip_header] = "chip_header",
  [sym_in_section] = "in_section",
  [sym_out_section] = "out_section",
  [sym_chip_body] = "chip_body",
  [sym_part] = "part",
  [sym_connection] = "connection",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_in_section_repeat1] = "in_section_repeat1",
  [aux_sym_out_section_repeat1] = "out_section_repeat1",
  [aux_sym_chip_body_repeat1] = "chip_body_repeat1",
  [aux_sym_part_repeat1] = "part_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CHIP] = anon_sym_CHIP,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_OUT] = anon_sym_OUT,
  [anon_sym_PARTS] = anon_sym_PARTS,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_chip_definition] = sym_chip_definition,
  [sym_chip_header] = sym_chip_header,
  [sym_in_section] = sym_in_section,
  [sym_out_section] = sym_out_section,
  [sym_chip_body] = sym_chip_body,
  [sym_part] = sym_part,
  [sym_connection] = sym_connection,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_in_section_repeat1] = aux_sym_in_section_repeat1,
  [aux_sym_out_section_repeat1] = aux_sym_out_section_repeat1,
  [aux_sym_chip_body_repeat1] = aux_sym_chip_body_repeat1,
  [aux_sym_part_repeat1] = aux_sym_part_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CHIP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PARTS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_chip_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_chip_header] = {
    .visible = true,
    .named = true,
  },
  [sym_in_section] = {
    .visible = true,
    .named = true,
  },
  [sym_out_section] = {
    .visible = true,
    .named = true,
  },
  [sym_chip_body] = {
    .visible = true,
    .named = true,
  },
  [sym_part] = {
    .visible = true,
    .named = true,
  },
  [sym_connection] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_in_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_out_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chip_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_part_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_chip_name = 2,
  field_chip_pin = 3,
  field_header = 4,
  field_input_pin_name = 5,
  field_name = 6,
  field_output_pin_name = 7,
  field_part_pin = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_chip_name] = "chip_name",
  [field_chip_pin] = "chip_pin",
  [field_header] = "header",
  [field_input_pin_name] = "input_pin_name",
  [field_name] = "name",
  [field_output_pin_name] = "output_pin_name",
  [field_part_pin] = "part_pin",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 1},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 1},
  [9] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_input_pin_name, 1},
  [1] =
    {field_body, 4},
    {field_header, 3},
    {field_name, 1},
  [4] =
    {field_input_pin_name, 1},
    {field_input_pin_name, 2, .inherited = true},
  [6] =
    {field_input_pin_name, 0, .inherited = true},
    {field_input_pin_name, 1, .inherited = true},
  [8] =
    {field_output_pin_name, 1},
  [9] =
    {field_output_pin_name, 1},
    {field_output_pin_name, 2, .inherited = true},
  [11] =
    {field_output_pin_name, 0, .inherited = true},
    {field_output_pin_name, 1, .inherited = true},
  [13] =
    {field_chip_name, 0},
  [14] =
    {field_chip_pin, 2},
    {field_part_pin, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '(', 26,
        ')', 27,
        ',', 21,
        '/', 2,
        ':', 25,
        ';', 22,
        '=', 28,
        'C', 7,
        'I', 9,
        'O', 15,
        'P', 6,
        '{', 18,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'H') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'I') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'N') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'P') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'S') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'U') ADVANCE(13);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_CHIP);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_OUT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PARTS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CHIP] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_OUT] = ACTIONS(1),
    [anon_sym_PARTS] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym__definition] = STATE(2),
    [sym_chip_definition] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_CHIP] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_CHIP,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(3), 3,
      sym__definition,
      sym_chip_definition,
      aux_sym_source_file_repeat1,
  [15] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_CHIP,
    STATE(3), 3,
      sym__definition,
      sym_chip_definition,
      aux_sym_source_file_repeat1,
  [30] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(16), 1,
      anon_sym_RBRACE,
    ACTIONS(18), 1,
      sym_identifier,
    STATE(5), 2,
      sym_part,
      aux_sym_chip_body_repeat1,
  [44] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      sym_identifier,
    ACTIONS(20), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_part,
      aux_sym_chip_body_repeat1,
  [58] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(22), 1,
      anon_sym_RBRACE,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(6), 2,
      sym_part,
      aux_sym_chip_body_repeat1,
  [72] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      aux_sym_part_repeat1,
  [85] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_in_section_repeat1,
  [98] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_in_section_repeat1,
  [111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_COMMA,
    ACTIONS(40), 1,
      anon_sym_SEMI,
    STATE(8), 1,
      aux_sym_in_section_repeat1,
  [124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      aux_sym_out_section_repeat1,
  [137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(46), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      aux_sym_out_section_repeat1,
  [150] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(14), 1,
      sym_connection,
  [163] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      aux_sym_part_repeat1,
  [176] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(57), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      aux_sym_out_section_repeat1,
  [189] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_IN,
    STATE(18), 1,
      sym_chip_header,
    STATE(20), 1,
      sym_in_section,
  [202] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      aux_sym_part_repeat1,
  [215] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PARTS,
    STATE(34), 1,
      sym_chip_body,
  [225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [233] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_OUT,
    STATE(38), 1,
      sym_out_section,
  [243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      anon_sym_CHIP,
  [251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [259] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(26), 1,
      sym_connection,
  [277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_PARTS,
  [316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_COLON,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
  [330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_identifier,
  [337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_PARTS,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
  [351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_SEMI,
  [358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_EQ,
  [365] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_identifier,
  [372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_PARTS,
  [379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identifier,
  [386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_OUT,
  [393] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_SEMI,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
  [407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
  [414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_identifier,
  [428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_SEMI,
  [435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      sym_identifier,
  [442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_OUT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 44,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 85,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 124,
  [SMALL_STATE(12)] = 137,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 163,
  [SMALL_STATE(15)] = 176,
  [SMALL_STATE(16)] = 189,
  [SMALL_STATE(17)] = 202,
  [SMALL_STATE(18)] = 215,
  [SMALL_STATE(19)] = 225,
  [SMALL_STATE(20)] = 233,
  [SMALL_STATE(21)] = 243,
  [SMALL_STATE(22)] = 251,
  [SMALL_STATE(23)] = 259,
  [SMALL_STATE(24)] = 267,
  [SMALL_STATE(25)] = 277,
  [SMALL_STATE(26)] = 285,
  [SMALL_STATE(27)] = 293,
  [SMALL_STATE(28)] = 301,
  [SMALL_STATE(29)] = 309,
  [SMALL_STATE(30)] = 316,
  [SMALL_STATE(31)] = 323,
  [SMALL_STATE(32)] = 330,
  [SMALL_STATE(33)] = 337,
  [SMALL_STATE(34)] = 344,
  [SMALL_STATE(35)] = 351,
  [SMALL_STATE(36)] = 358,
  [SMALL_STATE(37)] = 365,
  [SMALL_STATE(38)] = 372,
  [SMALL_STATE(39)] = 379,
  [SMALL_STATE(40)] = 386,
  [SMALL_STATE(41)] = 393,
  [SMALL_STATE(42)] = 400,
  [SMALL_STATE(43)] = 407,
  [SMALL_STATE(44)] = 414,
  [SMALL_STATE(45)] = 421,
  [SMALL_STATE(46)] = 428,
  [SMALL_STATE(47)] = 435,
  [SMALL_STATE(48)] = 442,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chip_body, 2, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chip_body, 3, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chip_body_repeat1, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chip_body_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_in_section_repeat1, 2, 0, 4), SHIFT_REPEAT(42),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_in_section_repeat1, 2, 0, 4),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_out_section_repeat1, 2, 0, 7), SHIFT_REPEAT(45),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_out_section_repeat1, 2, 0, 7),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_part_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_part_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_in_section_repeat1, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chip_definition, 6, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_part, 4, 0, 8),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_out_section_repeat1, 2, 0, 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connection, 3, 0, 9),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_part, 5, 0, 8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_part, 6, 0, 8),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_section, 3, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_section, 4, 0, 6),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chip_header, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_section, 4, 0, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_section, 3, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hdl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hdl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
